#!/system/bin/sh
# TailSocks Root Autostart Service Script

PKG="io.github.bropines.tailscaled.dev"
[ ! -d "/data/data/$PKG" ] && PKG="io.github.bropines.tailscaled"

DATA_DIR="/data/data/$PKG"
[ ! -d "$DATA_DIR" ] && exit 1

LOGS_DIR="$DATA_DIR/logs"
mkdir -p "$LOGS_DIR"

# State Directory Resolution:
# 1. Check default state dir
# 2. Search for any existing tailscaled.state in states/
# 3. Fallback to states/root
STATE_DIR="$DATA_DIR/files/states/default"
if [ ! -f "$STATE_DIR/tailscaled.state" ]; then
    FOUND_STATE="$(find "$DATA_DIR/files/states" -name "tailscaled.state" 2>/dev/null | head -n1)"
    if [ -n "$FOUND_STATE" ]; then
        STATE_DIR="$(dirname "$FOUND_STATE")"
    else
        STATE_DIR="$DATA_DIR/files/states/root"
    fi
fi
mkdir -p "$STATE_DIR"

SOCKET_PATH="$DATA_DIR/files/tailscaled.sock"
LOG_FILE="$LOGS_DIR/tailscaled.log"

# Find libtailscale.so binary across architectures
DAEMON_BIN="$(pm path $PKG 2>/dev/null | head -n1 | cut -d: -f2 | sed 's|base.apk|lib/x86_64/libtailscale.so|')"
[ ! -x "$DAEMON_BIN" ] && DAEMON_BIN="$(pm path $PKG 2>/dev/null | head -n1 | cut -d: -f2 | sed 's|base.apk|lib/arm64/libtailscale.so|')"
[ ! -x "$DAEMON_BIN" ] && DAEMON_BIN="$(pm path $PKG 2>/dev/null | head -n1 | cut -d: -f2 | sed 's|base.apk|lib/arm/libtailscale.so|')"
[ ! -x "$DAEMON_BIN" ] && DAEMON_BIN="$(pm path $PKG 2>/dev/null | head -n1 | cut -d: -f2 | sed 's|base.apk|lib/x86/libtailscale.so|')"
[ ! -x "$DAEMON_BIN" ] && DAEMON_BIN="$(find /data/app -name "libtailscale.so" 2>/dev/null | head -n1)"

if [ ! -x "$DAEMON_BIN" ]; then
    echo "TailSocks daemon binary not found" >> "$LOG_FILE"
    exit 1
fi

export TS_LOGS_DIR="$LOGS_DIR"
export TS_NO_LOGS_NO_SUPPORT=true
export TS_AUTH_ONCE=true
export TS_DNS_FALLBACK="1.1.1.1,8.8.8.8"

# Load control proxy environment variables if generated by TailSocks
if [ -f "$DATA_DIR/files/control_proxy.env" ]; then
    . "$DATA_DIR/files/control_proxy.env"
fi

# Log rotation: if log > 2MB, keep last 500 lines
if [ -f "$LOG_FILE" ]; then
    LOG_SIZE="$(wc -c < "$LOG_FILE" 2>/dev/null || echo 0)"
    if [ "$LOG_SIZE" -gt 2097152 ] 2>/dev/null; then
        tail -n 500 "$LOG_FILE" > "$LOG_FILE.tmp" && mv "$LOG_FILE.tmp" "$LOG_FILE"
    fi
fi

# Run daemon with resolved STATE_DIR (native safesocket patch forces 0666 on tailscaled.sock)
nohup "$DAEMON_BIN" --statedir="$STATE_DIR" --socket="$SOCKET_PATH" --tun=tailscale0 >> "$LOG_FILE" 2>&1 &
chmod 666 "$LOG_FILE" 2>/dev/null || true
magiskpolicy --live "allow untrusted_app magisk unix_stream_socket connectto" 2>/dev/null || supolicy --live "allow untrusted_app magisk unix_stream_socket connectto" 2>/dev/null || true
# Wait for daemon socket then apply table 1099 routing safely
for i in $(seq 1 30); do
    if [ -S "$SOCKET_PATH" ] || [ -e "$SOCKET_PATH" ]; then
        chmod 777 "$SOCKET_PATH"
        chcon u:object_r:app_data_file:s0 "$SOCKET_PATH" 2>/dev/null || true
        chmod 777 "$STATE_DIR" 2>/dev/null || true

        # Wait for tailscale0 and apply table 1099 policy routing
        for j in $(seq 1 30); do
            if ip link show tailscale0 >/dev/null 2>&1; then
                while ip rule del fwmark 1099 table 1099 2>/dev/null; do :; done
                while ip rule del fwmark 1099 lookup 1099 2>/dev/null; do :; done
                while iptables -t mangle -D OUTPUT -d 100.64.0.0/10 -j MARK --set-mark 1099 2>/dev/null; do :; done
                while iptables -D FORWARD -o tailscale0 -j ACCEPT 2>/dev/null; do :; done
                while iptables -D FORWARD -i tailscale0 -j ACCEPT 2>/dev/null; do :; done
                ip route del 100.64.0.0/10 dev tailscale0 table 1099 2>/dev/null || true

                ip route add 100.64.0.0/10 dev tailscale0 table 1099 metric 1 2>/dev/null || ip route add 100.64.0.0/10 dev tailscale0 metric 1
                iptables -t mangle -A OUTPUT -d 100.64.0.0/10 -j MARK --set-mark 1099 2>/dev/null || true
                ip rule add fwmark 1099 table 1099 priority 100 2>/dev/null || ip rule add fwmark 1099 table 1099 2>/dev/null || true
                iptables -I FORWARD -o tailscale0 -j ACCEPT 2>/dev/null || true
                iptables -I FORWARD -i tailscale0 -j ACCEPT 2>/dev/null || true
                iptables -t nat -I OUTPUT 1 -p udp --dport 53 -j DNAT --to-destination 100.100.100.100:53 2>/dev/null || true
                iptables -t nat -I OUTPUT 1 -p tcp --dport 53 -j DNAT --to-destination 100.100.100.100:53 2>/dev/null || true
                iptables -t nat -I OUTPUT 1 -d 100.64.0.0/10 -p udp --dport 53 -j ACCEPT 2>/dev/null || true
                iptables -t nat -I OUTPUT 1 -d 100.64.0.0/10 -p tcp --dport 53 -j ACCEPT 2>/dev/null || true
                break
            fi
            sleep 1
        done
        break
    fi
    sleep 0.2
done


